### ISSUE TITLE
Add a way to fetch base gas price from the blockchain

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-core#1641] opened 2024-02-01 17:39 UTC

**Comment by MitchTurner** [comment] 2024-02-08 20:48
I think this might be a dupe of these issues:
https://github.com/FuelLabs/fuel-core/issues/1647
https://github.com/FuelLabs/fuel-core/issues/1648

**Closed as completed** 2024-02-12 12:17 UTC
