### ISSUE TITLE
Remove all graphql schema (cynic) types from public interfaces (fuel-gql-client)

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-core#378] opened 2022-05-31 20:33 UTC
The public interfaces for fuel-gql-client both accept and return a mixture of custom data types and derived data types from the graphql schema using cynic. This isn't ideal because it couples cynic based traits and dependencies to users of the client. By wrapping all schema types that depend on cynic, it would be easier for the client to replace cynic and also shield the sdk from any breaking changes caused by newer versions of cynic.

**Comment by xgreenx** [comment] 2023-05-11 11:53
Duplicate of https://github.com/FuelLabs/fuel-core/issues/1121

**Closed by xgreenx** 2023-05-11 11:53 UTC
Labels: breaking
