### ISSUE TITLE
Improve dry-run API to validate all possible issues at once

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuel-core#1818] opened 2024-04-10 15:48 UTC
The idea is that the VM would ignore some rules and just dry-run the TX as best it can to completion. Each time some asset amount, contract, or variable UTXO is missing, it adds that to a log of missing data and continues the estimation run. All the missing data pieces encountered during the estimation call are discovered and returned in a single request to the API.

Implementing this solution would significantly reduce the number of total dry runs, relieving the burden on the SDK and node and allowing them to operate much faster, thereby enhancing execution efficiency for the users.

> [!NOTE]
> _One alternative is to run the VM via WASM to calculate everything. Still, since the WASM can be heavy in the MBs ballpark, it's currently not a feasible solution for front-end environments, so a change in the API could be a realistic solution._

cc @Voxelot @luizstacio

**Comment by xgreenx** [comment] 2024-04-10 15:55
Closing as a duplicate of the https://github.com/FuelLabs/fuel-vm/issues/691

**Closed by xgreenx** 2024-04-10 15:55 UTC
