### ISSUE TITLE
Replace the GraphQL interface with client-as-a-library and a minimal RPC

### ISSUE THREAD

**Issue by Dentosal** [FuelLabs/fuel-core#782] opened 2022-11-17 20:21 UTC
As discusses with the indexer team, we should be minimize the interface fuel-core exposes, and instead move the aggregate queries to the indexer.

**Comment by xgreenx** [comment] 2022-11-26 03:19
It is a duplicate of the https://github.com/FuelLabs/fuel-core/issues/588. We need to decide which issue will be main=)

**Comment by Voxelot** [comment] 2022-11-29 22:31
closing in favor of #588

**Closed by Voxelot** 2022-11-29 22:31 UTC
Labels: fuel-core, architecture, graphql-api
